//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSequence
    {
        public string SeqName { get; set; }
        public int Seed { get; set; }
        public int Incr { get; set; }
        public Nullable<int> Currval { get; set; }
    }
}
