//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int ChangeLogID { get; set; }
        public string ClassName { get; set; }
        public string PropertyName { get; set; }
        public string Key { get; set; }
        public string OriginalValue { get; set; }
        public string CurrentValue { get; set; }
        public string UserName { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
