//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public System.Guid EventLogID { get; set; }
        public int EventType { get; set; }
        public string Key { get; set; }
        public string Message { get; set; }
        public System.DateTime EntryDate { get; set; }
    }
}
