//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventory
    {
        public int ProductInventoryID { get; set; }
        public int ProductID { get; set; }
        public string LocationID { get; set; }
        public Nullable<long> OrderDetailID { get; set; }
        public int Quantity { get; set; }
        public string CreationUser { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Location Location { get; set; }
        public virtual Product Product { get; set; }
    }
}
